# Generated by Django 6.0.3 on 2026-04-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delayalerts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='delayalert',
            new_name='delayalerts_workspa_0861f1_idx',
            old_name='delayalerts__workspac_efb74c_idx',
        ),
        migrations.RenameIndex(
            model_name='delayalert',
            new_name='delayalerts_workspa_2338c3_idx',
            old_name='delayalerts__workspac_926469_idx',
        ),
        migrations.RenameIndex(
            model_name='taskprogress',
            new_name='delayalerts_workspa_1a14a5_idx',
            old_name='delayalerts__workspac_45aa17_idx',
        ),
        migrations.RenameIndex(
            model_name='taskprogress',
            new_name='delayalerts_workspa_83a34b_idx',
            old_name='delayalerts__workspac_48d8f9_idx',
        ),
    ]
