# Generated by Django 5.2.7 on 2025-12-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment_module', '0008_remove_managementuser_skills_alter_adminworkspace_id_and_more'),
        ('userstorymanager', '0002_remove_userstory_text_file_productowner_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='SprintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sprintmanager.sprint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstorymanager.backlog')),
            ],
        ),
    ]
