# Generated by Django 6.0.3 on 2026-04-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprintmanager', '0002_sprint_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='project_id',
        ),
    ]
