# Generated by Django 6.0.3 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintmanager', '0003_remove_sprint_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
