# Generated by Django 6.0 on 2025-12-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='userstorymanager.productowner')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('goal', models.TextField()),
                ('benefit', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='userstories/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='userstorymanager.productowner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='userstorymanager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('project_id', models.CharField(max_length=100)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('tasks', models.TextField()),
                ('subtasks', models.TextField()),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstorymanager.userstory')),
            ],
        ),
    ]
