# Generated by Django 5.2.7 on 2025-10-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('goal', models.TextField()),
                ('benefit', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=100)),
                ('text_file', models.FileField(upload_to='userstories/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='userstorymanager.productowner')),
            ],
        ),
    ]
