# Generated by Django 5.2.7 on 2025-12-10 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0008_remove_managementuser_skills_alter_adminworkspace_id_and_more'),
        ('userstorymanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='text_file',
        ),
        migrations.AddField(
            model_name='productowner',
            name='workspace',
            field=models.ForeignKey(blank=True, db_column='workspace_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_owners', to='assignment_module.adminworkspace'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='skills_required',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='user_story',
            field=models.ForeignKey(blank=True, db_column='user_story_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items', to='userstorymanager.userstory'),
        ),
    ]
