# Generated by Django 5.2.7 on 2025-10-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0002_userstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('project_id', models.CharField(max_length=100)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('tasks', models.TextField()),
                ('subtasks', models.TextField()),
                ('user_story_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items', to='userstorymanager.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='userstorymanager.productowner')),
            ],
        ),
    ]
