# Generated by Django 6.0.3 on 2026-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0002_remove_userstory_text_file_productowner_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
