# Generated by Django 5.2.7 on 2025-10-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0003_backlog_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='userstorymanager.project'),
        ),
    ]
