# Generated by Django 6.0.3 on 2026-04-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0003_project_workspace_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='workspace_id',
        ),
    ]
