# Generated by Django 5.2.7 on 2025-10-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0004_userstory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='userstories/'),
        ),
    ]
