# Generated by Django 6.0.3 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0004_add_email_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workspace_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
