# Generated by Django 5.2.7 on 2025-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0004_userstory_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='user_story_id',
            new_name='user_story',
        ),
    ]
