# Generated by Django 5.2.7 on 2025-10-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0005_rename_user_story_id_backlog_user_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backlog',
            old_name='user_story',
            new_name='user_story_id',
        ),
        migrations.AlterField(
            model_name='userstory',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='userstories/'),
        ),
    ]
