# Generated by Django 5.2.7 on 2025-10-29 16:30

from django.db import migrations


class Migration(migrations.Migration):
    # Leaving atomic False is fine; not required now that we don't use CONCURRENTLY.
    atomic = False

    dependencies = [
        ('userstorymanager', '0005_alter_userstory_text_file'),
    ]

    forward_sql = r"""
    -- 1) Ensure the column is physically named user_story_id
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='userstorymanager_backlog' AND column_name='user_story_id'
      ) THEN
        IF EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name='userstorymanager_backlog' AND column_name='user_story'
        ) THEN
          ALTER TABLE userstorymanager_backlog RENAME COLUMN user_story TO user_story_id;
        ELSE
          ALTER TABLE userstorymanager_backlog ADD COLUMN user_story_id bigint;
        END IF;
      END IF;
    END
    $$;

    -- 2) Enforce bigint type
    ALTER TABLE userstorymanager_backlog
      ALTER COLUMN user_story_id TYPE bigint USING user_story_id::bigint;

    -- 3) Add the FK if not already present (ON DELETE CASCADE)
    DO $$
    DECLARE
      fk_exists boolean;
    BEGIN
      SELECT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class t ON t.oid = c.conrelid
        WHERE t.relname = 'userstorymanager_backlog'
          AND c.contype = 'f'
          AND c.confrelid = 'userstorymanager_userstory'::regclass
          AND ARRAY['user_story_id']::text[] <@ (SELECT ARRAY_AGG(a.attname::text)
                                                FROM pg_attribute a
                                                WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey))
      ) INTO fk_exists;

      IF NOT fk_exists THEN
        ALTER TABLE userstorymanager_backlog
          ADD CONSTRAINT userstorymanager_backlog_user_story_id_fkey
          FOREIGN KEY (user_story_id)
          REFERENCES userstorymanager_userstory(id)
          ON DELETE CASCADE;
      END IF;
    END
    $$;

    -- 4) Helpful index on user_story_id (non-concurrent so it works inside the migration)
    CREATE INDEX IF NOT EXISTS
      userstorymanager_backlog_user_story_id_idx
    ON userstorymanager_backlog (user_story_id);
    """

    reverse_sql = r"""
    -- Drop index if exists
    DROP INDEX IF EXISTS userstorymanager_backlog_user_story_id_idx;

    -- Drop FK if exists
    DO $$
    DECLARE
      conname text;
    BEGIN
      SELECT conname
      INTO conname
      FROM pg_constraint c
      JOIN pg_class t ON t.oid = c.conrelid
      WHERE t.relname = 'userstorymanager_backlog'
        AND c.contype = 'f'
        AND c.confrelid = 'userstorymanager_userstory'::regclass
        AND ARRAY['user_story_id']::text[] <@ (SELECT ARRAY_AGG(a.attname::text)
                                              FROM pg_attribute a
                                              WHERE a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey))
      LIMIT 1;

      IF conname IS NOT NULL THEN
        EXECUTE format('ALTER TABLE userstorymanager_backlog DROP CONSTRAINT %I', conname);
      END IF;
    END
    $$;

    -- Rename back if rolling back
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='userstorymanager_backlog' AND column_name='user_story_id'
      ) THEN
        IF NOT EXISTS (
          SELECT 1 FROM information_schema.columns
          WHERE table_name='userstorymanager_backlog' AND column_name='user_story'
        ) THEN
          ALTER TABLE userstorymanager_backlog RENAME COLUMN user_story_id TO user_story;
        END IF;
      END IF;
    END
    $$;
    """

    operations = [
        migrations.RunSQL(sql=forward_sql, reverse_sql=reverse_sql),
    ]
