# Generated by Django 6.0.3 on 2026-04-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0002_userstory_story_points'),
        ('userstorymanager', '0005_project_workspace_id'),
    ]

    operations = [
    ]
