# Generated by Django 5.2.7 on 2025-10-29 16:40
from django.db import migrations


class Migration(migrations.Migration):
    # Not strictly required, but fine to keep.
    atomic = False

    dependencies = [
        ("userstorymanager", "0007_alter_backlog_user_story"),
    ]

    forward_sql = r"""
    -- Only run if the stray column exists
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='userstorymanager_backlog' AND column_name='user_story_id_id'
      ) THEN
        -- 1) Backfill any accidental values into the correct column
        UPDATE userstorymanager_backlog
        SET user_story_id = COALESCE(user_story_id, user_story_id_id::bigint)
        WHERE user_story_id IS NULL AND user_story_id_id IS NOT NULL;

        -- 2) Drop any FK that references the stray column
        DO $inner$
        DECLARE
          conname text;
        BEGIN
          SELECT c.conname
          INTO conname
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.conrelid
          JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
          WHERE t.relname = 'userstorymanager_backlog'
            AND c.contype = 'f'
            AND a.attname = 'user_story_id_id'
          LIMIT 1;

          IF conname IS NOT NULL THEN
            EXECUTE format('ALTER TABLE userstorymanager_backlog DROP CONSTRAINT %I', conname);
          END IF;
        END
        $inner$;

        -- 3) Drop the stray column
        ALTER TABLE userstorymanager_backlog DROP COLUMN IF EXISTS user_story_id_id;
      END IF;
    END
    $$;
    """

    reverse_sql = r"""
    -- No-op on reverse (we don't recreate the erroneous column)
    """

    operations = [
        migrations.RunSQL(sql=forward_sql, reverse_sql=reverse_sql),
    ]
