# Generated by Django 6.0.3 on 2026-04-04 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0007_project_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.IntegerField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_assignments', to='userstorymanager.productowner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_assignments', to='userstorymanager.project')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_assignments', to='userstorymanager.userstory')),
            ],
            options={
                'ordering': ['sprint_number', '-priority'],
                'unique_together': {('user_story', 'sprint_number', 'project')},
            },
        ),
    ]
