# Generated by Django 6.0 on 2025-12-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0006_rename_user_story_backlog_user_story_id_and_more'),
        ('userstorymanager', '0008_cleanup_backlog_user_story_id_id'),
    ]

    operations = [
    ]
