# Generated by Django 6.0 on 2025-12-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstorymanager', '0010_remove_backlog_user_story_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlog',
            name='user_story_id',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='text_file',
        ),
        migrations.AddField(
            model_name='backlog',
            name='user_story',
            field=models.ForeignKey(db_column='user_story_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_items', to='userstorymanager.userstory'),
            preserve_default=False,
        ),
    ]
