# Generated by Django 6.0 on 2025-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('skills', models.JSONField(default=list)),
                ('capacityHours', models.IntegerField(default=40)),
                ('assignedHours', models.IntegerField(default=0)),
                ('status', models.CharField(default='available', max_length=50)),
            ],
        ),
    ]
