# Generated by Django 6.0 on 2025-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('workspaceName', models.CharField(max_length=100)),
                ('companyName', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
