# Generated by Django 6.0 on 2025-12-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0002_adminworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
        ),
    ]
