# Generated by Django 6.0 on 2025-12-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0003_teammember_email_teammember_password_invitationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='password',
        ),
        migrations.AddField(
            model_name='teammember',
            name='workspace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='assignment_module.adminworkspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='assignment_module.adminworkspace'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
