# Generated by Django 6.0 on 2025-12-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0004_remove_teammember_password_teammember_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammember',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='assignment_module.adminworkspace'),
        ),
    ]
