# Generated by Django 6.0 on 2025-12-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0005_teammember_password_alter_teammember_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='assignedHours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='capacityHours',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('SCRUM_MASTER', 'Scrum Master'), ('PRODUCT_OWNER', 'Product Owner'), ('DEVELOPER', 'Developer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
