# Generated by Django 5.2.7 on 2025-12-10 23:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0007_remove_teammember_role_managementuser'),
        ('userstorymanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementuser',
            name='skills',
        ),
        migrations.AlterField(
            model_name='adminworkspace',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='managementuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.teammember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstorymanager.backlog')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'task', 'sprint_id'), name='unique_task_per_sprint')],
            },
        ),
    ]
