# Generated by Django 6.0.3 on 2026-04-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0009_auto_fix_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='workspace',
        ),
        migrations.RemoveConstraint(
            model_name='taskassignment',
            name='unique_task_per_sprint',
        ),
        migrations.AddField(
            model_name='teammember',
            name='Experience',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='Past_Projects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adminworkspace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='managementuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
