# Generated by Django 6.0.3 on 2026-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0014_remove_teammember_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='Experience',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='Past_Projects',
            field=models.TextField(blank=True),
        ),
    ]
