# Generated by Django 6.0.3 on 2026-04-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0015_teammember_experience_teammember_past_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default='DEVELOPER', max_length=20),
        ),
    ]
