# Generated by Django 6.0.3 on 2026-04-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0016_add_role_to_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
    ]
