# Generated by Django 6.0.3 on 2026-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0017_remove_role_from_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminworkspace',
            name='defaultCapacityHours',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='adminworkspace',
            name='defaultSprintLength',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='adminworkspace',
            name='defaultWorkingHoursPerWeek',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
