# Generated by Django 6.0.3 on 2026-04-04 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_module', '0018_add_scrum_config_to_workspace'),
        ('userstorymanager', '0001_initial'),  # Add dependency to userstorymanager
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='MANUAL', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.teammember')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstorymanager.backlog')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['workspace', 'task', 'sprint_id'], name='unique_task_per_sprint')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_module.adminworkspace')),
            ],
        ),
    ]
