# Generated by Django 6.0.3 on 2026-04-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskdependency', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='taskdepende_project_104a55_idx',
            old_name='taskdepende_project_5f92c6_idx',
        ),
        migrations.RenameIndex(
            model_name='taskdependency',
            new_name='taskdepende_project_f25ef1_idx',
            old_name='taskdepende_project_268745_idx',
        ),
    ]
